# running this is equivalent to running all the docker commands in the terminal separately
# - instead of executing docker run, docker volume, and docker network separately for these
#   two services we streamline the process by using this docker-compose.yml
services:
  # first service named postgres-db
  postgres-db:
    container_name: postgres-sql-rp0
    image: postgres
    env_file:
      - /.env/docker.env
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - rp0-bankapp-network
    restart: unless-stopped
  # second service named rp0-bankapp-api
  rp0-bankapp-api:
    container_name: rp0-bankapp-api
    image: rp0-bankapp-api:0.0.1-SNAPSHOT
    ports:
      - "8088:8080"
    env_file:
      - /.env/docker.env
    networks:
      - rp0-bankapp-network
    # waits for postgres-db to start before starting rp0-bankapp-api
    depends_on:
      - postgres-db
  # third service named rp0-bankapp-ui
  rp0-bankapp-ui:
    container_name: rp0-bankapp-ui
    image: rp0-bankapp-ui:0.0.0
    ports:
      - "80:80"
    networks:
      - rp0-bankapp-network
    depends_on:
      - rp0-bankapp-api

# equivalent to `docker network create bridge rp0-bankapp-network`
networks:
  rp0-bankapp-network:
    driver: bridge

# equivalent to `docker volume create postgres`
volumes:
  postgres:
    driver: local
