spring:
  profiles:
    active: dev
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    # show-sql: true
    # hibernate.ddl-auto: update
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000 # a day
  cors:
    # Use the value of `CORS_ORIGINS` env variable if it exists, if not, fall back to the default values
    origins: ${CORS_ORIGINS:http://localhost:4200,http://localhost}
server:
  port: ${PORT}